# Generated by Django 5.1.3 on 2024-11-25 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_applicant'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('JobTitle', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
                ('neededDegree', models.CharField(max_length=100)),
                ('neededExp', models.CharField(max_length=100)),
                ('neededApplicant', models.IntegerField(max_length=100)),
                ('neededRole', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('jobLabel', models.CharField(max_length=100)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.applicant')),
            ],
        ),
    ]
