# Generated by Django 5.1.3 on 2024-11-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_jobposting'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='createdBy',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
