# Generated by Django 5.1.3 on 2024-11-26 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_jobposting_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='applicant',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.applicant'),
        ),
    ]
