# Generated by Django 5.1.3 on 2024-11-26 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_jobposting_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.applicant'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='createdBy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='neededApplicant',
            field=models.IntegerField(),
        ),
    ]
