# Generated by Django 5.1.3 on 2024-12-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_applicant_birthplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='collegeGradDiploma',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='elemGradDiploma',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='postGradDiploma',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='secondaryGradDiploma',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='vocationalGradDiploma',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
