# Generated by Django 5.1.3 on 2024-12-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_applicant_collegegraddiploma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='emergencyContactcp',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='emergencyContactlandline',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='mobileNum',
            field=models.IntegerField(max_length=15),
        ),
    ]
