# Generated by Django 5.1.3 on 2024-12-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_applicant_emergencycontactcp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='fatherContact',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='mobileNum',
            field=models.CharField(max_length=15),
        ),
    ]
