# Generated by Django 5.1.3 on 2024-12-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_applicant_fathercontact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='jobLabel',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='neededExp',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='neededRole',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='employmentTime',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='jobdescription',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='location',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='neededApplicant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='neededDegree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
