# Generated by Django 5.1.3 on 2024-12-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_jobposting_joblabel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='jobdescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
