from django.db import models
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.contrib.auth.base_user import BaseUserManager
from django_rest_passwordreset.signals import reset_password_token_created
from django.dispatch import receiver
from django.urls import reverse
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives
from django.utils.html import strip_tags

class HrUserManager(BaseUserManager):
    def create_user(self, email, password=None, username=None):
        if not email:
            raise ValueError('An email is required.')
        if not password:
            raise ValueError('A password is required.')
        email = self.normalize_email(email)
        user = self.model(email=email, username=username)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password=None, username=None):
        if not email:
            raise ValueError('An email is required.')
        if not password:
            raise ValueError('A password is required.')
        user = self.create_user(email, password, username)
        user.is_superuser = True
        user.is_staff = True  # Superusers are usually staff as well
        user.save()
        return user


class Hruser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(max_length=50, unique=True)
    username = models.CharField(max_length=50) 
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    objects = HrUserManager()

    def __str__(self):
        return self.username

class Applicant(models.Model): 
    applicantID = models.AutoField( primary_key=True)
    fullname = models.CharField( max_length=50)
    emailAdd = models.EmailField( max_length=254)
    fb = models.CharField( max_length=250 , null=True, blank=True)
    presentAddress = models.CharField(max_length=100)
    permaAddress = models.CharField(max_length=100) 
    mobileNum = models.CharField(max_length=15)
    landline = models.IntegerField(max_length=12)
    sex = models.CharField(max_length=10)
    birthdate = models.CharField()
    civilStatus = models.CharField(max_length=12)
    height = models.CharField(max_length=24)
    weight = models.CharField(max_length=24)
    tin = models.IntegerField(max_length=24)
    philhealth = models.IntegerField(max_length=24)
    sss = models.IntegerField(max_length=24)
    pagibig = models.IntegerField(max_length=24)
    religion = models.CharField(max_length=100) 
    nationality = models.CharField(max_length=100) 
    promotions = models.CharField(max_length=100)
    referral = models.CharField(max_length=100)
    relationshipToReferral = models.CharField(max_length=100)
    language = models.CharField(max_length=100 , null= True , blank=True)
    Datebegin = models.DateField(max_length=100)
    salaryExpect = models.IntegerField(max_length=24)
    fathersName = models.CharField(max_length=100)
    mothersName = models.CharField(max_length=100)
    motherContact = models.IntegerField(max_length=24)
    fatherContact = models.CharField(max_length=24)
    famAddress = models.CharField(max_length=100)
    siblings1 = models.CharField(max_length=255, null=True, blank=True)
    siblings2 = models.CharField(max_length=255, null=True, blank=True)
    siblings3 = models.CharField(max_length=255, null=True, blank=True)
    siblings4 = models.CharField(max_length=255, null=True, blank=True)
    siblings5 = models.CharField(max_length=255, null=True, blank=True)
    siblings1Age = models.CharField(max_length=255, null=True, blank=True)
    siblings2Age = models.CharField(max_length=255, null=True, blank=True)
    siblings3Age = models.CharField(max_length=255, null=True, blank=True)
    siblings4Age = models.CharField(max_length=255, null=True, blank=True)
    siblings5Age = models.CharField(max_length=255, null=True, blank=True)
    siblings1Occupation = models.CharField(max_length=255, null=True, blank=True)
    siblings2Occupation = models.CharField(max_length=255, null=True, blank=True)
    siblings3Occupation = models.CharField(max_length=255, null=True, blank=True)
    siblings4Occupation = models.CharField(max_length=255, null=True, blank=True)
    siblings5Occupation = models.CharField(max_length=255, null=True, blank=True)
    siblings1Contact = models.CharField(max_length=255, null=True, blank=True)
    siblings2Contact = models.CharField(max_length=255, null=True, blank=True)
    siblings3Contact = models.CharField(max_length=255, null=True, blank=True)
    siblings4Contact = models.CharField(max_length=255, null=True, blank=True)
    siblings5Contact = models.CharField(max_length=255, null=True, blank=True)
    spousename = models.CharField(max_length=255, null=True, blank=True)
    spouseoccupation = models.CharField(max_length=255, null=True, blank=True)
    spousecontact = models.CharField(max_length=255, null=True, blank=True)
    spousenameemployer = models.CharField(max_length=255, null=True, blank=True)
    spouseaddress = models.CharField(max_length=255, null=True, blank=True)
    childnum = models.CharField(max_length=255, null=True, blank=True)
    childname1 = models.CharField(max_length=255, null=True, blank=True)
    childname2 = models.CharField(max_length=255, null=True, blank=True)
    childname3 = models.CharField(max_length=255, null=True, blank=True)
    childname4 = models.CharField(max_length=255, null=True, blank=True)
    childname5 = models.CharField(max_length=255, null=True, blank=True)
    childbirthdate1 = models.CharField(max_length=255, null=True, blank=True)
    childbirthdate2 = models.CharField(max_length=255, null=True, blank=True)
    childbirthdate3 = models.CharField(max_length=255, null=True, blank=True)
    childbirthdate4 = models.CharField(max_length=255, null=True, blank=True)
    childbirthdate5 = models.CharField(max_length=255, null=True, blank=True)
    childage1 = models.CharField(max_length=255, null=True, blank=True)
    childage2 = models.CharField(max_length=255, null=True, blank=True)
    childage3 = models.CharField(max_length=255, null=True, blank=True)
    childage4 = models.CharField(max_length=255, null=True, blank=True)
    childage5 = models.CharField(max_length=255, null=True, blank=True)
    emergencyContactName = models.CharField(max_length=100 , null=True, blank=True)
    emergencyContactRelationship = models.CharField(max_length=100 , null=True, blank=True)
    emergencyContactOccupation = models.CharField(max_length=100 , null=True, blank=True)
    emergencyContactemail = models.EmailField( max_length=254 , null=True, blank=True)
    emergencyContactcp = models.CharField( max_length=254 , null=True, blank=True)
    emergencyContactlandline = models.CharField( max_length=254 , null=True, blank=True)
    postSchoolName =models.CharField(max_length=255, null=True, blank=True)
    postSchoollocation =models.CharField(max_length=255, null=True, blank=True)
    postMajor =models.CharField(max_length=255, null=True, blank=True)
    postGradDateStarted =models.CharField(max_length=255, null=True, blank=True)
    postGradDateEnded =models.CharField(max_length=255, null=True, blank=True)
    postGradDiploma =models.CharField(max_length=255, null=True, blank=True)
    collegeSchoolName =models.CharField(max_length=255, null=True, blank=True)
    collegeSchoollocation =models.CharField(max_length=255, null=True, blank=True)
    collegeMajor =models.CharField(max_length=255, null=True, blank=True)
    collegeGradDateStarted =models.CharField(max_length=255, null=True, blank=True)
    collegeGradDateEnded =models.CharField(max_length=255, null=True, blank=True)
    collegeGradDiploma =models.CharField(max_length=255, null=True, blank=True)
    vocationalSchoolName =models.CharField(max_length=255, null=True, blank=True)
    vocationalSchoollocation =models.CharField(max_length=255, null=True, blank=True)
    vocationalMajor =models.CharField(max_length=255, null=True, blank=True)
    vocationalGradDateStarted =models.CharField(max_length=255, null=True, blank=True)
    vocationalGradDateEnded =models.CharField(max_length=255, null=True, blank=True)
    vocationalGradDiploma =models.CharField(max_length=255, null=True, blank=True)
    secondarySchoolName =models.CharField(max_length=255, null=True, blank=True)
    secondarySchoollocation =models.CharField(max_length=255, null=True, blank=True)
    secondaryMajor =models.CharField(max_length=255, null=True, blank=True)
    secondaryGradDateStarted =models.CharField(max_length=255, null=True, blank=True)
    secondaryGradDateEnded =models.CharField(max_length=255, null=True, blank=True)
    secondaryGradDiploma =models.CharField(max_length=255, null=True, blank=True)
    elemSchoolName =models.CharField(max_length=255, null=True, blank=True)
    elemSchoollocation =models.CharField(max_length=255, null=True, blank=True)
    elemMajor =models.CharField(max_length=255, null=True, blank=True)
    elemGradDateStarted =models.CharField(max_length=255, null=True, blank=True)
    elemGradDateEnded =models.CharField(max_length=255, null=True, blank=True)
    elemGradDiploma =models.CharField(max_length=255, null=True, blank=True)
    driverLicense = models.IntegerField(max_length=255, null=True, blank=True)
    ncee = models.IntegerField(max_length=255, null=True, blank=True)
    nsat = models.IntegerField(max_length=255, null=True, blank=True)
    licensure = models.IntegerField(max_length=255, null=True, blank=True)
    rating = models.IntegerField(max_length=255, null=True, blank=True)
    transpo = models.CharField(max_length=255, null=True, blank=True)
    employername1 =models.CharField(max_length=255, null=True, blank=True)
    workddress1 = models.CharField(max_length=255, null=True, blank=True)
    workdegree1 = models.CharField(max_length=255, null=True, blank=True)
    workdiploma1 = models.CharField(max_length=255, null=True, blank=True)
    workposition1 =models.CharField(max_length=255, null=True, blank=True)
    workpay1 = models.IntegerField(max_length=255, null=True, blank=True)
    workdatestart1 = models.CharField(max_length=255, null=True, blank=True)
    workdateend1 = models.CharField(max_length=255, null=True, blank=True)
    workphone1 = models.CharField(max_length=255, null=True, blank=True)
    worksupervisor1 = models.CharField(max_length=255, null=True, blank=True)
    workrole1 = models.CharField(max_length=255, null=True, blank=True)
    workleavereason1 = models.CharField(max_length=255, null=True, blank=True)
    employername2 =models.CharField(max_length=255, null=True, blank=True)
    workddress2 = models.CharField(max_length=255, null=True, blank=True)
    workdegree2 = models.CharField(max_length=255, null=True, blank=True)
    workdiploma2 = models.CharField(max_length=255, null=True, blank=True)
    workposition2 =models.CharField(max_length=255, null=True, blank=True)
    workpay2 = models.IntegerField(max_length=255, null=True, blank=True)
    workdatestart2 = models.CharField(max_length=255, null=True, blank=True)
    workdateend2 = models.CharField(max_length=255, null=True, blank=True)
    workphone2 = models.CharField(max_length=255, null=True, blank=True)
    worksupervisor2 = models.CharField(max_length=255, null=True, blank=True)
    workrole2 = models.CharField(max_length=255, null=True, blank=True)
    workleavereason2 = models.CharField(max_length=255, null=True, blank=True)
    employername3 =models.CharField(max_length=255, null=True, blank=True)
    workddress3 = models.CharField(max_length=255, null=True, blank=True)
    workdegree3 = models.CharField(max_length=255, null=True, blank=True)
    workdiploma3 = models.CharField(max_length=255, null=True, blank=True)
    workposition3 =models.CharField(max_length=255, null=True, blank=True)
    workpay3 = models.IntegerField(max_length=255, null=True, blank=True)
    workdatestart3 = models.CharField(max_length=255, null=True, blank=True)
    workdateend3 = models.CharField(max_length=255, null=True, blank=True)
    workphone3 = models.CharField(max_length=255, null=True, blank=True)
    worksupervisor3 = models.CharField(max_length=255, null=True, blank=True)
    workrole3 = models.CharField(max_length=255, null=True, blank=True)
    workleavereason3 = models.CharField(max_length=255, null=True, blank=True)
    seminar1 = models.IntegerField( null=True, blank=True)
    seminar2 = models.IntegerField( null=True, blank=True)
    seminar3 = models.IntegerField( null=True, blank=True)
    seminar4 = models.IntegerField( null=True, blank=True)
    seminar5 = models.IntegerField( null=True, blank=True)
    semplace1 = models.CharField(max_length=255, null=True, blank=True)
    semplace2 = models.CharField(max_length=255, null=True, blank=True)
    semplace3 = models.CharField(max_length=255, null=True, blank=True)
    semplace4 = models.CharField(max_length=255, null=True, blank=True)
    semplace5 = models.CharField(max_length=255, null=True, blank=True)
    semfrom1 = models.CharField(max_length=255, null=True, blank=True)
    semfrom2 = models.CharField(max_length=255, null=True, blank=True)
    semfrom3 = models.CharField(max_length=255, null=True, blank=True)
    semfrom4 = models.CharField(max_length=255, null=True, blank=True)
    semfrom5 = models.CharField(max_length=255, null=True, blank=True)
    semto1 = models.CharField(max_length=255, null=True, blank=True)
    semto2 = models.CharField(max_length=255, null=True, blank=True)
    semto3 = models.CharField(max_length=255, null=True, blank=True)
    semto4 = models.CharField(max_length=255, null=True, blank=True)
    semto5 = models.CharField(max_length=255, null=True, blank=True)
    organization1 = models.IntegerField( null=True, blank=True)
    organization2 = models.IntegerField( null=True, blank=True)
    organization3 = models.IntegerField( null=True, blank=True)
    organization4 = models.IntegerField( null=True, blank=True)
    organization5 = models.IntegerField( null=True, blank=True)
    orgplace1 = models.CharField(max_length=255, null=True, blank=True)
    orgplace2 = models.CharField(max_length=255, null=True, blank=True)
    orgplace3 = models.CharField(max_length=255, null=True, blank=True)
    orgplace4 = models.CharField(max_length=255, null=True, blank=True)
    orgplace5 = models.CharField(max_length=255, null=True, blank=True)
    orgfrom1 = models.CharField(max_length=255, null=True, blank=True)
    orgfrom2 = models.CharField(max_length=255, null=True, blank=True)
    orgfrom3 = models.CharField(max_length=255, null=True, blank=True)
    orgfrom4 = models.CharField(max_length=255, null=True, blank=True)
    orgfrom5 = models.CharField(max_length=255, null=True, blank=True)
    orgto1 = models.CharField(max_length=255, null=True, blank=True)
    orgto2 = models.CharField(max_length=255, null=True, blank=True)
    orgto3 = models.CharField(max_length=255, null=True, blank=True)
    orgto4 = models.CharField(max_length=255, null=True, blank=True)
    orgto5 = models.CharField(max_length=255, null=True, blank=True)
    reference1=models.CharField(max_length=100, null=True, blank=True)
    reference1Address=models.CharField(max_length=100, null=True, blank=True)
    reference1Cell=models.CharField(max_length=100, null=True, blank=True)
    reference1Landline=models.CharField(max_length=100, null=True, blank=True)
    reference1Relationship=models.CharField(max_length=100, null=True, blank=True)
    reference1Occupation=models.CharField(max_length=100, null=True, blank=True)
    reference2=models.CharField(max_length=100, null=True, blank=True)
    reference2Address=models.CharField(max_length=100, null=True, blank=True)
    reference2Cell=models.CharField(max_length=100, null=True, blank=True)
    reference2Landline=models.CharField(max_length=100, null=True, blank=True)
    reference2Relationship=models.CharField(max_length=100, null=True, blank=True)
    reference2Occupation=models.CharField(max_length=100, null=True, blank=True)
    reference3=models.CharField(max_length=100, null=True, blank=True)
    reference3Address=models.CharField(max_length=100, null=True, blank=True)
    reference3Cell=models.CharField(max_length=100, null=True, blank=True)
    reference3Landline=models.CharField(max_length=100, null=True, blank=True)
    reference3Relationship=models.CharField(max_length=100, null=True, blank=True)
    reference3Occupation=models.CharField(max_length=100, null=True, blank=True)
    referencerelativename1 =models.CharField(max_length=100, null=True, blank=True)
    referencerelativename2 =models.CharField(max_length=100, null=True, blank=True)
    referencerelativename3 =models.CharField(max_length=100, null=True, blank=True)
    referenceaddress1 =models.CharField(max_length=100, null=True, blank=True)
    referenceaddress2 =models.CharField(max_length=100, null=True, blank=True)
    referenceaddress3 =models.CharField(max_length=100, null=True, blank=True)
    referenceoccupation1 =models.CharField(max_length=100, null=True, blank=True)
    referenceoccupation2 =models.CharField(max_length=100, null=True, blank=True)
    referenceoccupation3 =models.CharField(max_length=100, null=True, blank=True)

class JobPosting(models.Model) : 
    JobTitle = models.CharField(max_length=100, primary_key=True)
    # ForeignKey with blank=True allows applicant to be optional
    applicant = models.ForeignKey(Applicant, on_delete=models.CASCADE, blank=True, null=True)
    department = models.CharField(max_length=100)
    neededDegree = models.CharField(max_length=100)
    neededExp = models.CharField(max_length=100)
    neededApplicant = models.IntegerField()  # IntegerField does not need max_length
    neededRole = models.CharField(max_length=100)
    status = models.CharField(max_length=100)
    jobLabel = models.CharField(max_length=100)
    createdBy = models.CharField(max_length=100, null=True, blank=True)
    
@receiver(reset_password_token_created)
def password_reset_token_created(reset_password_token , *args, **kwargs) : 
    sitelink = "https://192.168.254.112:5173/"
    token = "{}".format(reset_password_token.key)
    full_link = str(sitelink ) + str("password-reset/") + str(token)
    print(full_link)
    context = {
        'full_link':full_link , 
        "email_address" : reset_password_token.user.email
    }
    html_message = render_to_string("backend/email.html" , context=context)
    plain_message = strip_tags(html_message)
    msg = EmailMultiAlternatives (
        subject= "Request for resetting password for {title}".format(title = reset_password_token.user.email),
        body=plain_message,
        from_email="kalsnipe6@gmail.com",
        to=[reset_password_token.user.email]
    )
    msg.attach_alternative(html_message, "text/html")
    msg.send()