services:
  - type: web
    name: digihire-backend # Your project name
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn digihire.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: "your-secret-key-here"
      - key: DJANGO_DEBUG
        value: "false"
      - key: DATABASE_URL
        value: "postgres://<username>:<password>@<host>:<port>/<dbname>"
    plan: free
    autoDeploy: true
